on: 
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6.0.0

      - name: Docker Hub Login
        id: docker_login
        if: steps.checkout.outcome == 'success'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build and push
        if: steps.docker_login.outcome == 'success'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dave67000/daverepo:latest
